version: '3'
services:
  # redis-01配置
  redis-01:
    image: redis:5.0
    container_name: redis-01
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
      - 16379:16379
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    privileged: true # 拥有容器内命令执行的权限
    networks:
      - redis
    volumes:
      - ./conf/6379/redis.conf:/config/redis.conf
      - ./data/6379:/data
      - ./logs/6379:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
  # redis2配置
  redis-02:
    image: redis:5.0
    container_name: redis-02
    environment: # 环境变量
      - TZ=Asia/Shanghai
    ports:
      - 6380:6380
      - 16380:16380
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    privileged: true # 拥有容器内命令执行的权限
    networks:
      - redis
    volumes:
      - ./conf/6380/redis.conf:/config/redis.conf
      - ./data/6380:/data
      - ./logs/6380:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
  # redis-03配置
  redis3:
    image: redis:5.0
    container_name: redis-03
    environment: # 环境变量
      - TZ=Asia/Shanghai
    ports:
      - 6381:6381
      - 16381:16381
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    networks:
      - redis
    volumes:
      - ./conf/6381/redis.conf:/config/redis.conf
      - ./data/6381:/data
      - ./logs/6381:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
  # redis4配置
  redis-04:
    image: redis:5.0
    container_name: redis-04
    environment: # 环境变量
      - TZ=Asia/Shanghai
    ports:
      - 6382:6382
      - 16382:16382
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    networks:
      - redis
    volumes:
      - ./conf/6382/redis.conf:/config/redis.conf
      - ./data/6382:/data
      - ./logs/6382:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
  # redis5配置
  redis-05:
    image: redis:5.0
    container_name: redis-05
    environment: # 环境变量
      - TZ=Asia/Shanghai
    ports:
      - 6383:6383
      - 16383:16383    
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    networks:
      - redis
    volumes:
      - ./conf/6383/redis.conf:/config/redis.conf
      - ./data/6383:/data
      - ./logs/6383:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
  # redis6配置
  redis-06:
    image: redis:5.0
    container_name: redis-06
    environment: # 环境变量
      - TZ=Asia/Shanghai
    ports:
      - 6384:6384
      - 16384:16384    
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    networks:
      - redis
    volumes:
      - ./conf/6384/redis.conf:/config/redis.conf
      - ./data/6384:/data
      - ./logs/6384:/logs
    command: [ "redis-server", "/config/redis.conf" ] # 设置服务默认的启动命令
    
networks:
  redis:
    driver: bridge
    name: redis_cluster