version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - logs01:/usr/share/elasticsearch/logs
      - ./backup/snapshot:/usr/share/elasticsearch/backup
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./backup/config/es01/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - logs02:/usr/share/elasticsearch/logs
      - ./backup/snapshot:/usr/share/elasticsearch/backup
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./backup/config/es02/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - logs03:/usr/share/elasticsearch/logs
      - ./backup/snapshot:/usr/share/elasticsearch/backup
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./backup/config/es03/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
    networks:
      - elastic


  kibana:
    depends_on: 
      - es01
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
      
      
  es-head:
    depends_on: 
      - es01
    image: csucjh/elasticsearch-head:7
    container_name: es-head
    ports:
      - 9100:9100
    networks:
      - elastic 


  dejavu:
    image: appbaseio/dejavu
    container_name: dejavu
    ports:
      - 1358:1358
    links:
      - es01
    networks:
      - elastic


  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    ports:
        - 9000:9000
    command:
        - -Dhosts.0.host=http://es01:9200
    networks:
      - elastic
        

# 将data和logs使用本地挂载，在本地速度比较快，不然映射到宿主机目录卡的你怀疑人生
volumes:
  data01:
    driver: local
  logs01:
    driver: local
  data02:
    driver: local
  logs02:
    driver: local
  data03:
    driver: local
  logs03:
    driver: local

    

networks:
  elastic:
    #指定网络模式为桥接
    driver: bridge
    #指定网络名称，默认是目录名加上网络名称也就是elasticsearch_elastic
    name: es
